{% set name = "metaphlan" %}
{% set version = "4.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # url: https://github.com/biobakery/MetaPhlAn/archive/{{version}}.tar.gz
  # sha256: 3a86b7010f0b8e006ecb536fb56e85ebd1e7665360adb7ef840fdfd7108c3594
  # git_url: https://github.com/biobakery/MetaPhlAn.git
  # git_rev: 30c19aa97328a09e3e2c44baf89eaa0fa93cd93b
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-dependencies
  run_exports:
    - {{ pin_subpackage('metaphlan', max_pin='x.x') }}

requirements:
  host:
    - python >=3
    - setuptools
    - cython
    - numpy
  run:
    - python >=3
    - bowtie2 >=2.0.0
    - dendropy
    - numpy
    - phylophlan >=3.1
    - biom-format
    - matplotlib-base
    - biopython
    - pandas
    - scipy
    - requests
    - blast >=2.6.0
    - muscle >=3.8.1551
    - pysam
    - raxml >=8.2.10
    - samtools >=1.9
    - r-base >=4
    - r-essentials
    - r-optparse
    - r-rbiom
    - r-ape
    - r-compositions
    - r-biocmanager
    - bioconductor-microbiome
    - hclust2
test:
  commands:
    - metaphlan -v
    - strainphlan -v
    - extract_markers.py -h
    - merge_metaphlan_tables.py -h
    - read_fastx.py -h
    - add_metadata_tree.py -h
    - plot_tree_graphlan.py -h
    - sample2markers.py -h
    - strain_transmission.py -h
    - sgb_to_gtdb_profile.py -h
    - metaphlan2krona.py -h    
    - hclust2.py -h
    - run_treeshrink.py -h
    - treeshrink.py -h
    - create_toy_database.py -h
    - fix_relab_mpa4.py -h

about:
  home: https://github.com/biobakery/metaphlan
  license: MIT License
  license_family: MIT
  license_file: license.txt
  summary: Metagenomic Phylogenetic Analysis
  description: |
    MetaPhlAn is a computational tool for profiling the composition of microbial
    communities (Bacteria, Archaea and Eukaryotes) from metagenomic
    shotgun sequencing data with species level resolution. From version 2.0
    MetaPhlAn is also able to identify specific strains (in the not-so-frequent
    cases in which the sample contains a previously sequenced strains) and to
    track strains across samples for all species.
