# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build MetaPhlAn package

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip install numpy scipy cython
        sudo apt install bowtie2 muscle ncbi-blast+ raxml minimap2
        pip install .
    - name: Test 
      run: |
        metaphlan -v
        strainphlan -h
        extract_markers.py -h
        merge_metaphlan_tables.py -h
        read_fastx.py -h
        add_metadata_tree.py -h
        plot_tree_graphlan.py -h
        sample2markers.py -h
        strain_transmission.py -h
